/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables.records;


import cn.edu.kmust.flst.domain.tables.Banner;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BannerRecord extends UpdatableRecordImpl<BannerRecord> implements Record6<Integer, String, Timestamp, Byte, String, String> {

    private static final long serialVersionUID = -312551368;

    /**
     * Setter for <code>flst.banner.banner_id</code>.
     */
    public void setBannerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>flst.banner.banner_id</code>.
     */
    public Integer getBannerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>flst.banner.banner_link</code>.
     */
    public void setBannerLink(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>flst.banner.banner_link</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getBannerLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flst.banner.banner_date</code>.
     */
    public void setBannerDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>flst.banner.banner_date</code>.
     */
    @NotNull
    public Timestamp getBannerDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>flst.banner.banner_show</code>.
     */
    public void setBannerShow(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>flst.banner.banner_show</code>.
     */
    public Byte getBannerShow() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>flst.banner.menu_id</code>.
     */
    public void setMenuId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>flst.banner.menu_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getMenuId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>flst.banner.username</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>flst.banner.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Byte, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Byte, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Banner.BANNER.BANNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Banner.BANNER.BANNER_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Banner.BANNER.BANNER_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Banner.BANNER.BANNER_SHOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Banner.BANNER.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Banner.BANNER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBannerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBannerLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getBannerDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getBannerShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBannerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBannerLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getBannerDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getBannerShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value1(Integer value) {
        setBannerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value2(String value) {
        setBannerLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value3(Timestamp value) {
        setBannerDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value4(Byte value) {
        setBannerShow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value5(String value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value6(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord values(Integer value1, String value2, Timestamp value3, Byte value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerRecord
     */
    public BannerRecord() {
        super(Banner.BANNER);
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(Integer bannerId, String bannerLink, Timestamp bannerDate, Byte bannerShow, String menuId, String username) {
        super(Banner.BANNER);

        set(0, bannerId);
        set(1, bannerLink);
        set(2, bannerDate);
        set(3, bannerShow);
        set(4, menuId);
        set(5, username);
    }
}
