/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.tables.records;


import cn.edu.kmust.flst.domain.tables.Banner;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerRecord extends UpdatableRecordImpl<BannerRecord> implements Record5<Integer, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = 1472038452;

    /**
     * Setter for <code>flst.banner.banner_id</code>.
     */
    public void setBannerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>flst.banner.banner_id</code>.
     */
    public Integer getBannerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>flst.banner.banner_link</code>.
     */
    public void setBannerLink(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>flst.banner.banner_link</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getBannerLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flst.banner.banner_order</code>.
     */
    public void setBannerOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>flst.banner.banner_order</code>.
     */
    @NotNull
    public Integer getBannerOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>flst.banner.banner_date</code>.
     */
    public void setBannerDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>flst.banner.banner_date</code>.
     */
    @NotNull
    public Timestamp getBannerDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>flst.banner.menu_id</code>.
     */
    public void setMenuId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>flst.banner.menu_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getMenuId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Banner.BANNER.BANNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Banner.BANNER.BANNER_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Banner.BANNER.BANNER_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Banner.BANNER.BANNER_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Banner.BANNER.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBannerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBannerLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getBannerOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getBannerDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBannerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBannerLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBannerOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getBannerDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value1(Integer value) {
        setBannerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value2(String value) {
        setBannerLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value3(Integer value) {
        setBannerOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value4(Timestamp value) {
        setBannerDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value5(String value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord values(Integer value1, String value2, Integer value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerRecord
     */
    public BannerRecord() {
        super(Banner.BANNER);
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(Integer bannerId, String bannerLink, Integer bannerOrder, Timestamp bannerDate, String menuId) {
        super(Banner.BANNER);

        set(0, bannerId);
        set(1, bannerLink);
        set(2, bannerOrder);
        set(3, bannerDate);
        set(4, menuId);
    }
}
