/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionState implements Serializable {

    private static final long serialVersionUID = 936292907;

    private String key;
    private String sql;

    public SessionState() {}

    public SessionState(SessionState value) {
        this.key = value.key;
        this.sql = value.sql;
    }

    public SessionState(
        String key,
        String sql
    ) {
        this.key = key;
        this.sql = sql;
    }

    @Size(max = 2147483647)
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @Size(max = 2147483647)
    public String getSql() {
        return this.sql;
    }

    public void setSql(String sql) {
        this.sql = sql;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SessionState (");

        sb.append(key);
        sb.append(", ").append(sql);

        sb.append(")");
        return sb.toString();
    }
}
