/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings implements Serializable {

    private static final long serialVersionUID = 2009151070;

    private String name;
    private String value;

    public Settings() {}

    public Settings(Settings value) {
        this.name = value.name;
        this.value = value.value;
    }

    public Settings(
        String name,
        String value
    ) {
        this.name = name;
        this.value = value;
    }

    @Size(max = 2147483647)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 2147483647)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Settings (");

        sb.append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
