/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain;


import cn.edu.kmust.flst.domain.tables.Authorities;
import cn.edu.kmust.flst.domain.tables.PersistentLogins;
import cn.edu.kmust.flst.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in flst
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flst.authorities</code>.
     */
    public static final Authorities AUTHORITIES = cn.edu.kmust.flst.domain.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>flst.persistent_logins</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = cn.edu.kmust.flst.domain.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>flst.users</code>.
     */
    public static final Users USERS = cn.edu.kmust.flst.domain.tables.Users.USERS;
}
