spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/flst?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

---
spring:
   profiles: prod
   datasource:
     url: jdbc:mysql://localhost/flst?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: root
     password: 123456