flst:
  constants:
    document-root:
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jooq:
    sql-dialect: mysql

server:
  port: 8080