flst:
  constants:
    document-root: root
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jooq:
    sql-dialect: mysql
  datasource:
    url: jdbc:mysql://localhost/flst?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","file://${user.dir}/${flst.constants.document-root}/${flst.constants.static-images}"]

server:
  port: 9731
  undertow:
    accesslog:
      dir: logs
      enabled: true