# spring setting
spring:
      profiles:
        active: dev
      servlet:
              multipart:
                max-request-size: 100MB
                max-file-size: 100MB
      thymeleaf:
        mode: HTML
      cache:
        cache-names:
        caffeine:
          spec: maximumSize=500,expireAfterAccess=600s

# logging setting
logging:
  file: flst.log
  path: logs

# server setting
server:
  compression:
    enabled: true
    min-response-size: 1
