flst:
  constants:
    document-root:
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jooq:
    sql-dialect: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080