flst:
  constants:
    document-root: root
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jooq:
    sql-dialect: h2
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","file://${user.dir}/${flst.constants.document-root}/${flst.constants.static-images}"]

server:
  port: 9734
  undertow:
    accesslog:
      dir: logs
      enabled: true