/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ArticleContent implements Serializable {

    private static final long serialVersionUID = -1813680856;

    private Integer id;
    private String articleContent;

    public ArticleContent() {
    }

    public ArticleContent(ArticleContent value) {
        this.id = value.id;
        this.articleContent = value.articleContent;
    }

    public ArticleContent(
            Integer id,
            String articleContent
    ) {
        this.id = id;
        this.articleContent = articleContent;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @NotNull
    public String getArticleContent() {
        return this.articleContent;
    }

    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleContent (");

        sb.append(id);
        sb.append(", ").append(articleContent);

        sb.append(")");
        return sb.toString();
    }
}
