/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 337730592;

    private Integer   articleId;
    private String    articleTitle;
    private String    articleBrief;
    private String    articleCover;
    private Timestamp articleDate;
    private Integer   articleClicks;
    private String    articleAuthor;
    private Integer   articleSources;
    private String    articleSourcesName;
    private String    articleSourcesLink;
    private Integer   articleSn;
    private String    menuId;

    public Article() {}

    public Article(Article value) {
        this.articleId = value.articleId;
        this.articleTitle = value.articleTitle;
        this.articleBrief = value.articleBrief;
        this.articleCover = value.articleCover;
        this.articleDate = value.articleDate;
        this.articleClicks = value.articleClicks;
        this.articleAuthor = value.articleAuthor;
        this.articleSources = value.articleSources;
        this.articleSourcesName = value.articleSourcesName;
        this.articleSourcesLink = value.articleSourcesLink;
        this.articleSn = value.articleSn;
        this.menuId = value.menuId;
    }

    public Article(
        Integer   articleId,
        String    articleTitle,
        String    articleBrief,
        String    articleCover,
        Timestamp articleDate,
        Integer   articleClicks,
        String    articleAuthor,
        Integer   articleSources,
        String    articleSourcesName,
        String    articleSourcesLink,
        Integer   articleSn,
        String    menuId
    ) {
        this.articleId = articleId;
        this.articleTitle = articleTitle;
        this.articleBrief = articleBrief;
        this.articleCover = articleCover;
        this.articleDate = articleDate;
        this.articleClicks = articleClicks;
        this.articleAuthor = articleAuthor;
        this.articleSources = articleSources;
        this.articleSourcesName = articleSourcesName;
        this.articleSourcesLink = articleSourcesLink;
        this.articleSn = articleSn;
        this.menuId = menuId;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    @NotNull
    @Size(max = 100)
    public String getArticleTitle() {
        return this.articleTitle;
    }

    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    @Size(max = 200)
    public String getArticleBrief() {
        return this.articleBrief;
    }

    public void setArticleBrief(String articleBrief) {
        this.articleBrief = articleBrief;
    }

    @Size(max = 200)
    public String getArticleCover() {
        return this.articleCover;
    }

    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover;
    }

    @NotNull
    public Timestamp getArticleDate() {
        return this.articleDate;
    }

    public void setArticleDate(Timestamp articleDate) {
        this.articleDate = articleDate;
    }

    public Integer getArticleClicks() {
        return this.articleClicks;
    }

    public void setArticleClicks(Integer articleClicks) {
        this.articleClicks = articleClicks;
    }

    @NotNull
    @Size(max = 64)
    public String getArticleAuthor() {
        return this.articleAuthor;
    }

    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor;
    }

    public Integer getArticleSources() {
        return this.articleSources;
    }

    public void setArticleSources(Integer articleSources) {
        this.articleSources = articleSources;
    }

    @Size(max = 100)
    public String getArticleSourcesName() {
        return this.articleSourcesName;
    }

    public void setArticleSourcesName(String articleSourcesName) {
        this.articleSourcesName = articleSourcesName;
    }

    @Size(max = 200)
    public String getArticleSourcesLink() {
        return this.articleSourcesLink;
    }

    public void setArticleSourcesLink(String articleSourcesLink) {
        this.articleSourcesLink = articleSourcesLink;
    }

    public Integer getArticleSn() {
        return this.articleSn;
    }

    public void setArticleSn(Integer articleSn) {
        this.articleSn = articleSn;
    }

    @NotNull
    @Size(max = 64)
    public String getMenuId() {
        return this.menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(articleId);
        sb.append(", ").append(articleTitle);
        sb.append(", ").append(articleBrief);
        sb.append(", ").append(articleCover);
        sb.append(", ").append(articleDate);
        sb.append(", ").append(articleClicks);
        sb.append(", ").append(articleAuthor);
        sb.append(", ").append(articleSources);
        sb.append(", ").append(articleSourcesName);
        sb.append(", ").append(articleSourcesLink);
        sb.append(", ").append(articleSn);
        sb.append(", ").append(menuId);

        sb.append(")");
        return sb.toString();
    }
}
