/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Banner implements Serializable {

    private static final long serialVersionUID = 1791602611;

    private Integer bannerId;
    private String bannerLink;
    private Timestamp bannerDate;
    private Byte bannerShow;
    private String menuId;
    private String username;

    public Banner() {
    }

    public Banner(Banner value) {
        this.bannerId = value.bannerId;
        this.bannerLink = value.bannerLink;
        this.bannerDate = value.bannerDate;
        this.bannerShow = value.bannerShow;
        this.menuId = value.menuId;
        this.username = value.username;
    }

    public Banner(
            Integer bannerId,
            String bannerLink,
            Timestamp bannerDate,
            Byte bannerShow,
            String menuId,
            String username
    ) {
        this.bannerId = bannerId;
        this.bannerLink = bannerLink;
        this.bannerDate = bannerDate;
        this.bannerShow = bannerShow;
        this.menuId = menuId;
        this.username = username;
    }

    public Integer getBannerId() {
        return this.bannerId;
    }

    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    @NotNull
    @Size(max = 200)
    public String getBannerLink() {
        return this.bannerLink;
    }

    public void setBannerLink(String bannerLink) {
        this.bannerLink = bannerLink;
    }

    @NotNull
    public Timestamp getBannerDate() {
        return this.bannerDate;
    }

    public void setBannerDate(Timestamp bannerDate) {
        this.bannerDate = bannerDate;
    }

    public Byte getBannerShow() {
        return this.bannerShow;
    }

    public void setBannerShow(Byte bannerShow) {
        this.bannerShow = bannerShow;
    }

    @NotNull
    @Size(max = 64)
    public String getMenuId() {
        return this.menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Banner (");

        sb.append(bannerId);
        sb.append(", ").append(bannerLink);
        sb.append(", ").append(bannerDate);
        sb.append(", ").append(bannerShow);
        sb.append(", ").append(menuId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
