/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables.daos;


import cn.edu.kmust.flst.domain.tables.DataInfo;
import cn.edu.kmust.flst.domain.tables.records.DataInfoRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class DataInfoDao extends DAOImpl<DataInfoRecord, cn.edu.kmust.flst.domain.tables.pojos.DataInfo, String> {

    /**
     * Create a new DataInfoDao without any configuration
     */
    public DataInfoDao() {
        super(DataInfo.DATA_INFO, cn.edu.kmust.flst.domain.tables.pojos.DataInfo.class);
    }

    /**
     * Create a new DataInfoDao with an attached configuration
     */
    @Autowired
    public DataInfoDao(Configuration configuration) {
        super(DataInfo.DATA_INFO, cn.edu.kmust.flst.domain.tables.pojos.DataInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.edu.kmust.flst.domain.tables.pojos.DataInfo object) {
        return object.getDataKey();
    }

    /**
     * Fetch records that have <code>data_key IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.DataInfo> fetchByDataKey(String... values) {
        return fetch(DataInfo.DATA_INFO.DATA_KEY, values);
    }

    /**
     * Fetch a unique record that has <code>data_key = value</code>
     */
    public cn.edu.kmust.flst.domain.tables.pojos.DataInfo fetchOneByDataKey(String value) {
        return fetchOne(DataInfo.DATA_INFO.DATA_KEY, value);
    }

    /**
     * Fetch records that have <code>data_value IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.DataInfo> fetchByDataValue(String... values) {
        return fetch(DataInfo.DATA_INFO.DATA_VALUE, values);
    }
}
