/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables.daos;


import cn.edu.kmust.flst.domain.tables.FriendlyLink;
import cn.edu.kmust.flst.domain.tables.records.FriendlyLinkRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class FriendlyLinkDao extends DAOImpl<FriendlyLinkRecord, cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink, String> {

    /**
     * Create a new FriendlyLinkDao without any configuration
     */
    public FriendlyLinkDao() {
        super(FriendlyLink.FRIENDLY_LINK, cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink.class);
    }

    /**
     * Create a new FriendlyLinkDao with an attached configuration
     */
    @Autowired
    public FriendlyLinkDao(Configuration configuration) {
        super(FriendlyLink.FRIENDLY_LINK, cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink object) {
        return object.getLinkId();
    }

    /**
     * Fetch records that have <code>link_id IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink> fetchByLinkId(String... values) {
        return fetch(FriendlyLink.FRIENDLY_LINK.LINK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>link_id = value</code>
     */
    public cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink fetchOneByLinkId(String value) {
        return fetchOne(FriendlyLink.FRIENDLY_LINK.LINK_ID, value);
    }

    /**
     * Fetch records that have <code>link_name IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink> fetchByLinkName(String... values) {
        return fetch(FriendlyLink.FRIENDLY_LINK.LINK_NAME, values);
    }

    /**
     * Fetch records that have <code>link_name_en IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink> fetchByLinkNameEn(String... values) {
        return fetch(FriendlyLink.FRIENDLY_LINK.LINK_NAME_EN, values);
    }

    /**
     * Fetch records that have <code>link_url IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink> fetchByLinkUrl(String... values) {
        return fetch(FriendlyLink.FRIENDLY_LINK.LINK_URL, values);
    }

    /**
     * Fetch records that have <code>link_show IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.FriendlyLink> fetchByLinkShow(Byte... values) {
        return fetch(FriendlyLink.FRIENDLY_LINK.LINK_SHOW, values);
    }
}
