/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.tables.daos;


import cn.edu.kmust.flst.domain.tables.Menus;
import cn.edu.kmust.flst.domain.tables.records.MenusRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class MenusDao extends DAOImpl<MenusRecord, cn.edu.kmust.flst.domain.tables.pojos.Menus, String> {

    /**
     * Create a new MenusDao without any configuration
     */
    public MenusDao() {
        super(Menus.MENUS, cn.edu.kmust.flst.domain.tables.pojos.Menus.class);
    }

    /**
     * Create a new MenusDao with an attached configuration
     */
    @Autowired
    public MenusDao(Configuration configuration) {
        super(Menus.MENUS, cn.edu.kmust.flst.domain.tables.pojos.Menus.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.edu.kmust.flst.domain.tables.pojos.Menus object) {
        return object.getMenuId();
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuId(String... values) {
        return fetch(Menus.MENUS.MENU_ID, values);
    }

    /**
     * Fetch a unique record that has <code>menu_id = value</code>
     */
    public cn.edu.kmust.flst.domain.tables.pojos.Menus fetchOneByMenuId(String value) {
        return fetchOne(Menus.MENUS.MENU_ID, value);
    }

    /**
     * Fetch records that have <code>menu_name IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuName(String... values) {
        return fetch(Menus.MENUS.MENU_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>menu_name = value</code>
     */
    public cn.edu.kmust.flst.domain.tables.pojos.Menus fetchOneByMenuName(String value) {
        return fetchOne(Menus.MENUS.MENU_NAME, value);
    }

    /**
     * Fetch records that have <code>menu_name_en IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuNameEn(String... values) {
        return fetch(Menus.MENUS.MENU_NAME_EN, values);
    }

    /**
     * Fetch a unique record that has <code>menu_name_en = value</code>
     */
    public cn.edu.kmust.flst.domain.tables.pojos.Menus fetchOneByMenuNameEn(String value) {
        return fetchOne(Menus.MENUS.MENU_NAME_EN, value);
    }

    /**
     * Fetch records that have <code>out_link IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByOutLink(Byte... values) {
        return fetch(Menus.MENUS.OUT_LINK, values);
    }

    /**
     * Fetch records that have <code>menu_link IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuLink(String... values) {
        return fetch(Menus.MENUS.MENU_LINK, values);
    }

    /**
     * Fetch records that have <code>menu_pid IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuPid(String... values) {
        return fetch(Menus.MENUS.MENU_PID, values);
    }

    /**
     * Fetch records that have <code>menu_order IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuOrder(Integer... values) {
        return fetch(Menus.MENUS.MENU_ORDER, values);
    }

    /**
     * Fetch records that have <code>menu_show IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuShow(Byte... values) {
        return fetch(Menus.MENUS.MENU_SHOW, values);
    }

    /**
     * Fetch records that have <code>menu_fixed IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuFixed(Byte... values) {
        return fetch(Menus.MENUS.MENU_FIXED, values);
    }

    /**
     * Fetch records that have <code>show_article IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByShowArticle(Byte... values) {
        return fetch(Menus.MENUS.SHOW_ARTICLE, values);
    }

    /**
     * Fetch records that have <code>menu_creator IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.tables.pojos.Menus> fetchByMenuCreator(String... values) {
        return fetch(Menus.MENUS.MENU_CREATOR, values);
    }
}
