/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.public_;


import cn.edu.kmust.flst.domain.public_.tables.Article;
import cn.edu.kmust.flst.domain.public_.tables.ArticleContent;
import cn.edu.kmust.flst.domain.public_.tables.ArticleEn;
import cn.edu.kmust.flst.domain.public_.tables.ArticleEnContent;
import cn.edu.kmust.flst.domain.public_.tables.Authorities;
import cn.edu.kmust.flst.domain.public_.tables.Banner;
import cn.edu.kmust.flst.domain.public_.tables.DataInfo;
import cn.edu.kmust.flst.domain.public_.tables.Files;
import cn.edu.kmust.flst.domain.public_.tables.FriendlyLink;
import cn.edu.kmust.flst.domain.public_.tables.Menus;
import cn.edu.kmust.flst.domain.public_.tables.PersistentLogins;
import cn.edu.kmust.flst.domain.public_.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ARTICLE</code>.
     */
    public static final Article ARTICLE = cn.edu.kmust.flst.domain.public_.tables.Article.ARTICLE;

    /**
     * The table <code>PUBLIC.ARTICLE_CONTENT</code>.
     */
    public static final ArticleContent ARTICLE_CONTENT = cn.edu.kmust.flst.domain.public_.tables.ArticleContent.ARTICLE_CONTENT;

    /**
     * The table <code>PUBLIC.ARTICLE_EN</code>.
     */
    public static final ArticleEn ARTICLE_EN = cn.edu.kmust.flst.domain.public_.tables.ArticleEn.ARTICLE_EN;

    /**
     * The table <code>PUBLIC.ARTICLE_EN_CONTENT</code>.
     */
    public static final ArticleEnContent ARTICLE_EN_CONTENT = cn.edu.kmust.flst.domain.public_.tables.ArticleEnContent.ARTICLE_EN_CONTENT;

    /**
     * The table <code>PUBLIC.AUTHORITIES</code>.
     */
    public static final Authorities AUTHORITIES = cn.edu.kmust.flst.domain.public_.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>PUBLIC.BANNER</code>.
     */
    public static final Banner BANNER = cn.edu.kmust.flst.domain.public_.tables.Banner.BANNER;

    /**
     * The table <code>PUBLIC.DATA_INFO</code>.
     */
    public static final DataInfo DATA_INFO = cn.edu.kmust.flst.domain.public_.tables.DataInfo.DATA_INFO;

    /**
     * The table <code>PUBLIC.FILES</code>.
     */
    public static final Files FILES = cn.edu.kmust.flst.domain.public_.tables.Files.FILES;

    /**
     * The table <code>PUBLIC.FRIENDLY_LINK</code>.
     */
    public static final FriendlyLink FRIENDLY_LINK = cn.edu.kmust.flst.domain.public_.tables.FriendlyLink.FRIENDLY_LINK;

    /**
     * The table <code>PUBLIC.MENUS</code>.
     */
    public static final Menus MENUS = cn.edu.kmust.flst.domain.public_.tables.Menus.MENUS;

    /**
     * The table <code>PUBLIC.PERSISTENT_LOGINS</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = cn.edu.kmust.flst.domain.public_.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = cn.edu.kmust.flst.domain.public_.tables.Users.USERS;
}
