/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.public_.tables.daos;


import cn.edu.kmust.flst.domain.public_.tables.ArticleEnContent;
import cn.edu.kmust.flst.domain.public_.tables.records.ArticleEnContentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ArticleEnContentDao extends DAOImpl<ArticleEnContentRecord, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent, Integer> {

    /**
     * Create a new ArticleEnContentDao without any configuration
     */
    public ArticleEnContentDao() {
        super(ArticleEnContent.ARTICLE_EN_CONTENT, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent.class);
    }

    /**
     * Create a new ArticleEnContentDao with an attached configuration
     */
    @Autowired
    public ArticleEnContentDao(Configuration configuration) {
        super(ArticleEnContent.ARTICLE_EN_CONTENT, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent> fetchById(Integer... values) {
        return fetch(ArticleEnContent.ARTICLE_EN_CONTENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent fetchOneById(Integer value) {
        return fetchOne(ArticleEnContent.ARTICLE_EN_CONTENT.ID, value);
    }

    /**
     * Fetch records that have <code>article_content IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleEnContent> fetchByArticleContent(String... values) {
        return fetch(ArticleEnContent.ARTICLE_EN_CONTENT.ARTICLE_CONTENT, values);
    }
}
