/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.public_.tables.daos;


import cn.edu.kmust.flst.domain.public_.tables.ArticleContent;
import cn.edu.kmust.flst.domain.public_.tables.records.ArticleContentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ArticleContentDao extends DAOImpl<ArticleContentRecord, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent, Integer> {

    /**
     * Create a new ArticleContentDao without any configuration
     */
    public ArticleContentDao() {
        super(ArticleContent.ARTICLE_CONTENT, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent.class);
    }

    /**
     * Create a new ArticleContentDao with an attached configuration
     */
    @Autowired
    public ArticleContentDao(Configuration configuration) {
        super(ArticleContent.ARTICLE_CONTENT, cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent> fetchById(Integer... values) {
        return fetch(ArticleContent.ARTICLE_CONTENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent fetchOneById(Integer value) {
        return fetchOne(ArticleContent.ARTICLE_CONTENT.ID, value);
    }

    /**
     * Fetch records that have <code>ARTICLE_CONTENT IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.ArticleContent> fetchByArticleContent(String... values) {
        return fetch(ArticleContent.ARTICLE_CONTENT.ARTICLE_CONTENT_, values);
    }
}
