/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.public_.tables.daos;


import cn.edu.kmust.flst.domain.public_.tables.Banner;
import cn.edu.kmust.flst.domain.public_.tables.records.BannerRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BannerDao extends DAOImpl<BannerRecord, cn.edu.kmust.flst.domain.public_.tables.pojos.Banner, Integer> {

    /**
     * Create a new BannerDao without any configuration
     */
    public BannerDao() {
        super(Banner.BANNER, cn.edu.kmust.flst.domain.public_.tables.pojos.Banner.class);
    }

    /**
     * Create a new BannerDao with an attached configuration
     */
    @Autowired
    public BannerDao(Configuration configuration) {
        super(Banner.BANNER, cn.edu.kmust.flst.domain.public_.tables.pojos.Banner.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.edu.kmust.flst.domain.public_.tables.pojos.Banner object) {
        return object.getBannerId();
    }

    /**
     * Fetch records that have <code>banner_id IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerId(Integer... values) {
        return fetch(Banner.BANNER.BANNER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>banner_id = value</code>
     */
    public cn.edu.kmust.flst.domain.public_.tables.pojos.Banner fetchOneByBannerId(Integer value) {
        return fetchOne(Banner.BANNER.BANNER_ID, value);
    }

    /**
     * Fetch records that have <code>banner_link IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerLink(String... values) {
        return fetch(Banner.BANNER.BANNER_LINK, values);
    }

    /**
     * Fetch records that have <code>banner_date IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerDate(Timestamp... values) {
        return fetch(Banner.BANNER.BANNER_DATE, values);
    }

    /**
     * Fetch records that have <code>banner_show IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerShow(Boolean... values) {
        return fetch(Banner.BANNER.BANNER_SHOW, values);
    }

    /**
     * Fetch records that have <code>banner_title IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerTitle(String... values) {
        return fetch(Banner.BANNER.BANNER_TITLE, values);
    }

    /**
     * Fetch records that have <code>banner_title_en IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerTitleEn(String... values) {
        return fetch(Banner.BANNER.BANNER_TITLE_EN, values);
    }

    /**
     * Fetch records that have <code>banner_brief IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerBrief(String... values) {
        return fetch(Banner.BANNER.BANNER_BRIEF, values);
    }

    /**
     * Fetch records that have <code>banner_brief_en IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerBriefEn(String... values) {
        return fetch(Banner.BANNER.BANNER_BRIEF_EN, values);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByMenuId(String... values) {
        return fetch(Banner.BANNER.MENU_ID, values);
    }

    /**
     * Fetch records that have <code>banner_creator IN (values)</code>
     */
    public List<cn.edu.kmust.flst.domain.public_.tables.pojos.Banner> fetchByBannerCreator(String... values) {
        return fetch(Banner.BANNER.BANNER_CREATOR, values);
    }
}
