/*
 * This file is generated by jOOQ.
 */
package cn.edu.kmust.flst.domain.tables;


import cn.edu.kmust.flst.domain.Flst;
import cn.edu.kmust.flst.domain.Indexes;
import cn.edu.kmust.flst.domain.Keys;
import cn.edu.kmust.flst.domain.tables.records.ArticleEnRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ArticleEn extends TableImpl<ArticleEnRecord> {

    private static final long serialVersionUID = 1902726266;

    /**
     * The reference instance of <code>flst.article_en</code>
     */
    public static final ArticleEn ARTICLE_EN = new ArticleEn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleEnRecord> getRecordType() {
        return ArticleEnRecord.class;
    }

    /**
     * The column <code>flst.article_en.article_id</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>flst.article_en.article_title</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_TITLE = createField("article_title", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>flst.article_en.article_brief</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_BRIEF = createField("article_brief", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>flst.article_en.article_cover</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_COVER = createField("article_cover", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>flst.article_en.article_content</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_CONTENT = createField("article_content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>flst.article_en.article_date</code>.
     */
    public final TableField<ArticleEnRecord, Timestamp> ARTICLE_DATE = createField("article_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>flst.article_en.article_clicks</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_CLICKS = createField("article_clicks", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>flst.article_en.username</code>.
     */
    public final TableField<ArticleEnRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>flst.article_en.article_sources</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_SOURCES = createField("article_sources", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>flst.article_en.article_sources_name</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_SOURCES_NAME = createField("article_sources_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>flst.article_en.article_sources_link</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_SOURCES_LINK = createField("article_sources_link", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>flst.article_en.menu_id</code>.
     */
    public final TableField<ArticleEnRecord, String> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * Create a <code>flst.article_en</code> table reference
     */
    public ArticleEn() {
        this(DSL.name("article_en"), null);
    }

    /**
     * Create an aliased <code>flst.article_en</code> table reference
     */
    public ArticleEn(String alias) {
        this(DSL.name(alias), ARTICLE_EN);
    }

    /**
     * Create an aliased <code>flst.article_en</code> table reference
     */
    public ArticleEn(Name alias) {
        this(alias, ARTICLE_EN);
    }

    private ArticleEn(Name alias, Table<ArticleEnRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleEn(Name alias, Table<ArticleEnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Flst.FLST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ARTICLE_EN_MENU_ID, Indexes.ARTICLE_EN_PRIMARY, Indexes.ARTICLE_EN_USERNAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ArticleEnRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ARTICLE_EN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ArticleEnRecord> getPrimaryKey() {
        return Keys.KEY_ARTICLE_EN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ArticleEnRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticleEnRecord>>asList(Keys.KEY_ARTICLE_EN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ArticleEnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ArticleEnRecord, ?>>asList(Keys.ARTICLE_EN_IBFK_2, Keys.ARTICLE_EN_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEn as(String alias) {
        return new ArticleEn(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEn as(Name alias) {
        return new ArticleEn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEn rename(String name) {
        return new ArticleEn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEn rename(Name name) {
        return new ArticleEn(name, null);
    }
}
