/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.flst.tables;


import cn.edu.kmust.flst.domain.flst.Flst;
import cn.edu.kmust.flst.domain.flst.Indexes;
import cn.edu.kmust.flst.domain.flst.Keys;
import cn.edu.kmust.flst.domain.flst.tables.records.ArticleEnRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleEn extends TableImpl<ArticleEnRecord> {

    private static final long serialVersionUID = -531392529;

    /**
     * The reference instance of <code>FLST.ARTICLE_EN</code>
     */
    public static final ArticleEn ARTICLE_EN = new ArticleEn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleEnRecord> getRecordType() {
        return ArticleEnRecord.class;
    }

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_ID</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_ID = createField("ARTICLE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_TITLE</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_TITLE = createField("ARTICLE_TITLE", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_BRIEF</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_BRIEF = createField("ARTICLE_BRIEF", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_COVER</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_COVER = createField("ARTICLE_COVER", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_DATE</code>.
     */
    public final TableField<ArticleEnRecord, Timestamp> ARTICLE_DATE = createField("ARTICLE_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_CLICKS</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_CLICKS = createField("ARTICLE_CLICKS", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_AUTHOR</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_AUTHOR = createField("ARTICLE_AUTHOR", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_SOURCES</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_SOURCES = createField("ARTICLE_SOURCES", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_SOURCES_NAME</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_SOURCES_NAME = createField("ARTICLE_SOURCES_NAME", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_SOURCES_LINK</code>.
     */
    public final TableField<ArticleEnRecord, String> ARTICLE_SOURCES_LINK = createField("ARTICLE_SOURCES_LINK", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.ARTICLE_SN</code>.
     */
    public final TableField<ArticleEnRecord, Integer> ARTICLE_SN = createField("ARTICLE_SN", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN.MENU_ID</code>.
     */
    public final TableField<ArticleEnRecord, String> MENU_ID = createField("MENU_ID", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * Create a <code>FLST.ARTICLE_EN</code> table reference
     */
    public ArticleEn() {
        this(DSL.name("ARTICLE_EN"), null);
    }

    /**
     * Create an aliased <code>FLST.ARTICLE_EN</code> table reference
     */
    public ArticleEn(String alias) {
        this(DSL.name(alias), ARTICLE_EN);
    }

    /**
     * Create an aliased <code>FLST.ARTICLE_EN</code> table reference
     */
    public ArticleEn(Name alias) {
        this(alias, ARTICLE_EN);
    }

    private ArticleEn(Name alias, Table<ArticleEnRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleEn(Name alias, Table<ArticleEnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Flst.FLST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_2, Indexes.CONSTRAINT_INDEX_26, Indexes.PRIMARY_KEY_26);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ArticleEnRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ARTICLE_EN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ArticleEnRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_26;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ArticleEnRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticleEnRecord>>asList(Keys.CONSTRAINT_26);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ArticleEnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ArticleEnRecord, ?>>asList(Keys.CONSTRAINT_26BF, Keys.CONSTRAINT_26B);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEn as(String alias) {
        return new ArticleEn(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEn as(Name alias) {
        return new ArticleEn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEn rename(String name) {
        return new ArticleEn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEn rename(Name name) {
        return new ArticleEn(name, null);
    }
}
