/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.flst.tables;


import cn.edu.kmust.flst.domain.flst.Flst;
import cn.edu.kmust.flst.domain.flst.Indexes;
import cn.edu.kmust.flst.domain.flst.Keys;
import cn.edu.kmust.flst.domain.flst.tables.records.ArticleEnContentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleEnContent extends TableImpl<ArticleEnContentRecord> {

    private static final long serialVersionUID = -769514174;

    /**
     * The reference instance of <code>FLST.ARTICLE_EN_CONTENT</code>
     */
    public static final ArticleEnContent ARTICLE_EN_CONTENT = new ArticleEnContent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleEnContentRecord> getRecordType() {
        return ArticleEnContentRecord.class;
    }

    /**
     * The column <code>FLST.ARTICLE_EN_CONTENT.ID</code>.
     */
    public final TableField<ArticleEnContentRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLST.ARTICLE_EN_CONTENT.ARTICLE_CONTENT</code>.
     */
    public final TableField<ArticleEnContentRecord, String> ARTICLE_CONTENT = createField("ARTICLE_CONTENT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>FLST.ARTICLE_EN_CONTENT</code> table reference
     */
    public ArticleEnContent() {
        this(DSL.name("ARTICLE_EN_CONTENT"), null);
    }

    /**
     * Create an aliased <code>FLST.ARTICLE_EN_CONTENT</code> table reference
     */
    public ArticleEnContent(String alias) {
        this(DSL.name(alias), ARTICLE_EN_CONTENT);
    }

    /**
     * Create an aliased <code>FLST.ARTICLE_EN_CONTENT</code> table reference
     */
    public ArticleEnContent(Name alias) {
        this(alias, ARTICLE_EN_CONTENT);
    }

    private ArticleEnContent(Name alias, Table<ArticleEnContentRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleEnContent(Name alias, Table<ArticleEnContentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Flst.FLST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ArticleEnContentRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ArticleEnContentRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticleEnContentRecord>>asList(Keys.CONSTRAINT_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ArticleEnContentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ArticleEnContentRecord, ?>>asList(Keys.CONSTRAINT_97);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEnContent as(String alias) {
        return new ArticleEnContent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleEnContent as(Name alias) {
        return new ArticleEnContent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEnContent rename(String name) {
        return new ArticleEnContent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleEnContent rename(Name name) {
        return new ArticleEnContent(name, null);
    }
}
