/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.flst.tables;


import cn.edu.kmust.flst.domain.flst.Flst;
import cn.edu.kmust.flst.domain.flst.Indexes;
import cn.edu.kmust.flst.domain.flst.Keys;
import cn.edu.kmust.flst.domain.flst.tables.records.DataInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataInfo extends TableImpl<DataInfoRecord> {

    private static final long serialVersionUID = 212383226;

    /**
     * The reference instance of <code>FLST.DATA_INFO</code>
     */
    public static final DataInfo DATA_INFO = new DataInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataInfoRecord> getRecordType() {
        return DataInfoRecord.class;
    }

    /**
     * The column <code>FLST.DATA_INFO.DATA_KEY</code>.
     */
    public final TableField<DataInfoRecord, String> DATA_KEY = createField("DATA_KEY", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>FLST.DATA_INFO.DATA_VALUE</code>.
     */
    public final TableField<DataInfoRecord, String> DATA_VALUE = createField("DATA_VALUE", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * Create a <code>FLST.DATA_INFO</code> table reference
     */
    public DataInfo() {
        this(DSL.name("DATA_INFO"), null);
    }

    /**
     * Create an aliased <code>FLST.DATA_INFO</code> table reference
     */
    public DataInfo(String alias) {
        this(DSL.name(alias), DATA_INFO);
    }

    /**
     * Create an aliased <code>FLST.DATA_INFO</code> table reference
     */
    public DataInfo(Name alias) {
        this(alias, DATA_INFO);
    }

    private DataInfo(Name alias, Table<DataInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private DataInfo(Name alias, Table<DataInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Flst.FLST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_92);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DataInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_92;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DataInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<DataInfoRecord>>asList(Keys.CONSTRAINT_92);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataInfo as(String alias) {
        return new DataInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataInfo as(Name alias) {
        return new DataInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataInfo rename(String name) {
        return new DataInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataInfo rename(Name name) {
        return new DataInfo(name, null);
    }
}
