/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.flst;


import cn.edu.kmust.flst.domain.flst.tables.Article;
import cn.edu.kmust.flst.domain.flst.tables.ArticleContent;
import cn.edu.kmust.flst.domain.flst.tables.ArticleEn;
import cn.edu.kmust.flst.domain.flst.tables.ArticleEnContent;
import cn.edu.kmust.flst.domain.flst.tables.Authorities;
import cn.edu.kmust.flst.domain.flst.tables.Banner;
import cn.edu.kmust.flst.domain.flst.tables.DataInfo;
import cn.edu.kmust.flst.domain.flst.tables.Files;
import cn.edu.kmust.flst.domain.flst.tables.FriendlyLink;
import cn.edu.kmust.flst.domain.flst.tables.Menus;
import cn.edu.kmust.flst.domain.flst.tables.PersistentLogins;
import cn.edu.kmust.flst.domain.flst.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in FLST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>FLST.ARTICLE</code>.
     */
    public static final Article ARTICLE = cn.edu.kmust.flst.domain.flst.tables.Article.ARTICLE;

    /**
     * The table <code>FLST.ARTICLE_CONTENT</code>.
     */
    public static final ArticleContent ARTICLE_CONTENT = cn.edu.kmust.flst.domain.flst.tables.ArticleContent.ARTICLE_CONTENT;

    /**
     * The table <code>FLST.ARTICLE_EN</code>.
     */
    public static final ArticleEn ARTICLE_EN = cn.edu.kmust.flst.domain.flst.tables.ArticleEn.ARTICLE_EN;

    /**
     * The table <code>FLST.ARTICLE_EN_CONTENT</code>.
     */
    public static final ArticleEnContent ARTICLE_EN_CONTENT = cn.edu.kmust.flst.domain.flst.tables.ArticleEnContent.ARTICLE_EN_CONTENT;

    /**
     * The table <code>FLST.AUTHORITIES</code>.
     */
    public static final Authorities AUTHORITIES = cn.edu.kmust.flst.domain.flst.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>FLST.BANNER</code>.
     */
    public static final Banner BANNER = cn.edu.kmust.flst.domain.flst.tables.Banner.BANNER;

    /**
     * The table <code>FLST.DATA_INFO</code>.
     */
    public static final DataInfo DATA_INFO = cn.edu.kmust.flst.domain.flst.tables.DataInfo.DATA_INFO;

    /**
     * The table <code>FLST.FILES</code>.
     */
    public static final Files FILES = cn.edu.kmust.flst.domain.flst.tables.Files.FILES;

    /**
     * The table <code>FLST.FRIENDLY_LINK</code>.
     */
    public static final FriendlyLink FRIENDLY_LINK = cn.edu.kmust.flst.domain.flst.tables.FriendlyLink.FRIENDLY_LINK;

    /**
     * The table <code>FLST.MENUS</code>.
     */
    public static final Menus MENUS = cn.edu.kmust.flst.domain.flst.tables.Menus.MENUS;

    /**
     * The table <code>FLST.PERSISTENT_LOGINS</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = cn.edu.kmust.flst.domain.flst.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>FLST.USERS</code>.
     */
    public static final Users USERS = cn.edu.kmust.flst.domain.flst.tables.Users.USERS;
}
