/*
 * This file is generated by jOOQ.
*/
package cn.edu.kmust.flst.domain.flst.tables.records;


import cn.edu.kmust.flst.domain.flst.tables.Article;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record12<Integer, String, String, String, Timestamp, Integer, String, Integer, String, String, Integer, String> {

    private static final long serialVersionUID = -1032397993;

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_ID</code>.
     */
    public void setArticleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_ID</code>.
     */
    public Integer getArticleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_TITLE</code>.
     */
    public void setArticleTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_TITLE</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getArticleTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_BRIEF</code>.
     */
    public void setArticleBrief(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_BRIEF</code>.
     */
    @Size(max = 200)
    public String getArticleBrief() {
        return (String) get(2);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_COVER</code>.
     */
    public void setArticleCover(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_COVER</code>.
     */
    @Size(max = 200)
    public String getArticleCover() {
        return (String) get(3);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_DATE</code>.
     */
    public void setArticleDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_DATE</code>.
     */
    @NotNull
    public Timestamp getArticleDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_CLICKS</code>.
     */
    public void setArticleClicks(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_CLICKS</code>.
     */
    public Integer getArticleClicks() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_AUTHOR</code>.
     */
    public void setArticleAuthor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_AUTHOR</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getArticleAuthor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_SOURCES</code>.
     */
    public void setArticleSources(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_SOURCES</code>.
     */
    public Integer getArticleSources() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_SOURCES_NAME</code>.
     */
    public void setArticleSourcesName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_SOURCES_NAME</code>.
     */
    @Size(max = 100)
    public String getArticleSourcesName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_SOURCES_LINK</code>.
     */
    public void setArticleSourcesLink(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_SOURCES_LINK</code>.
     */
    @Size(max = 200)
    public String getArticleSourcesLink() {
        return (String) get(9);
    }

    /**
     * Setter for <code>FLST.ARTICLE.ARTICLE_SN</code>.
     */
    public void setArticleSn(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.ARTICLE_SN</code>.
     */
    public Integer getArticleSn() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>FLST.ARTICLE.MENU_ID</code>.
     */
    public void setMenuId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>FLST.ARTICLE.MENU_ID</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getMenuId() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Timestamp, Integer, String, Integer, String, String, Integer, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Timestamp, Integer, String, Integer, String, String, Integer, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Article.ARTICLE.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Article.ARTICLE.ARTICLE_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Article.ARTICLE.ARTICLE_BRIEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Article.ARTICLE.ARTICLE_COVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Article.ARTICLE.ARTICLE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Article.ARTICLE.ARTICLE_CLICKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Article.ARTICLE.ARTICLE_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Article.ARTICLE.ARTICLE_SOURCES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Article.ARTICLE.ARTICLE_SOURCES_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Article.ARTICLE.ARTICLE_SOURCES_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Article.ARTICLE.ARTICLE_SN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Article.ARTICLE.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getArticleTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getArticleBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getArticleCover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getArticleDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getArticleClicks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getArticleAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getArticleSources();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getArticleSourcesName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getArticleSourcesLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getArticleSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getArticleTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getArticleBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getArticleCover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getArticleDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getArticleClicks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getArticleAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getArticleSources();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getArticleSourcesName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getArticleSourcesLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getArticleSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value1(Integer value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value2(String value) {
        setArticleTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value3(String value) {
        setArticleBrief(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value4(String value) {
        setArticleCover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value5(Timestamp value) {
        setArticleDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value6(Integer value) {
        setArticleClicks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value7(String value) {
        setArticleAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value8(Integer value) {
        setArticleSources(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value9(String value) {
        setArticleSourcesName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value10(String value) {
        setArticleSourcesLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value11(Integer value) {
        setArticleSn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value12(String value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Integer value6, String value7, Integer value8, String value9, String value10, Integer value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Integer articleId, String articleTitle, String articleBrief, String articleCover, Timestamp articleDate, Integer articleClicks, String articleAuthor, Integer articleSources, String articleSourcesName, String articleSourcesLink, Integer articleSn, String menuId) {
        super(Article.ARTICLE);

        set(0, articleId);
        set(1, articleTitle);
        set(2, articleBrief);
        set(3, articleCover);
        set(4, articleDate);
        set(5, articleClicks);
        set(6, articleAuthor);
        set(7, articleSources);
        set(8, articleSourcesName);
        set(9, articleSourcesLink);
        set(10, articleSn);
        set(11, menuId);
    }
}
